import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translations object
const translations = {
  es: {
    // Header
    'header.home': 'Inicio',
    'header.services': 'Servicios',
    'header.team': 'Equipo',
    'header.clients': 'Clientes',
    'header.contact': 'Contacto',
    'header.getStarted': 'Comenzar',
    
    // Hero
    'hero.location': 'Popayán, Cauca, Colombia',
    'hero.title': 'Transformando Ideas en',
    'hero.titleHighlight': 'Soluciones Digitales',
    'hero.subtitle': 'Somos Modware, una empresa colombiana de desarrollo de software especializada en aplicaciones personalizadas, soluciones de IA y transformación digital.',
    'hero.exploreServices': 'Explorar Servicios',
    'hero.startProject': 'Iniciar Proyecto',
    'hero.developers': 'Desarrolladores Expertos',
    'hero.projects': 'Proyectos Entregados',
    'hero.clients': 'Clientes Satisfechos',
    'hero.experience': 'Años de Experiencia',
    
    // Services
    'services.title': 'Nuestros',
    'services.titleHighlight': 'Servicios',
    'services.subtitle': 'Ofrecemos servicios integrales de desarrollo de software para ayudar a tu negocio a prosperar en la era digital. Desde aplicaciones personalizadas hasta soluciones de IA.',
    'services.cta.title': '¿Listo para Transformar tu Negocio?',
    'services.cta.subtitle': 'Hablemos sobre cómo nuestra experiencia puede ayudarte a alcanzar tus objetivos digitales. Obtén una consulta gratuita y estimación del proyecto.',
    'services.cta.consultation': 'Consulta Gratuita',
    'services.cta.quote': 'Solicitar Cotización',
    'services.technologies': 'Tecnologías que Dominamos',
    
    // SEO
    'seo.title': 'Desarrollo de Software en Colombia',
    'seo.subtitle': 'Somos una empresa colombiana especializada en desarrollo de aplicaciones móviles, web y soluciones de inteligencia artificial para empresas de todos los tamaños.',
    'seo.mobile.title': 'Desarrollo de Aplicaciones Móviles',
    'seo.mobile.description': 'Creamos aplicaciones móviles nativas e híbridas para iOS y Android utilizando las últimas tecnologías como Flutter, React Native y desarrollo nativo.',
    'seo.web.title': 'Desarrollo Web Profesional',
    'seo.web.description': 'Desarrollamos sitios web y aplicaciones web modernas, responsivas y optimizadas para SEO utilizando tecnologías como React, Angular, Vue.js y Node.js.',
    'seo.ai.title': 'Inteligencia Artificial y Machine Learning',
    'seo.ai.description': 'Implementamos soluciones de IA personalizadas, chatbots inteligentes, análisis de datos y automatización de procesos empresariales.',
    'seo.company.title': 'Sobre Modware',
    'seo.company.about.title': 'Nuestra Empresa',
    'seo.company.about.description': 'Modware es una empresa de desarrollo de software con sede en Colombia, especializada en crear soluciones tecnológicas innovadoras para empresas de todos los sectores.',
    'seo.company.about.location': 'Bogotá, Colombia',
    'seo.company.about.team': 'Equipo de desarrolladores expertos',
    'seo.company.about.projects': 'Proyectos exitosos entregados',
    'seo.company.services.title': 'Nuestros Servicios',
    'seo.company.services.mobile': 'Desarrollo de aplicaciones móviles iOS y Android',
    'seo.company.services.web': 'Desarrollo web con React, Angular y Vue.js',
    'seo.company.services.ai': 'Soluciones de inteligencia artificial',
    'seo.company.services.consulting': 'Consultoría en transformación digital',
    'seo.company.services.support': 'Mantenimiento y soporte técnico',
    
    // Team translations
    'team.title': 'Conoce a Nuestro',
    'team.titleHighlight': 'Equipo Experto',
    'team.subtitle': 'Nuestro talentoso equipo de desarrolladores, diseñadores y científicos de datos están apasionados por crear soluciones innovadoras que impulsan el éxito empresarial.',
    'team.stats.title': '¿Por qué elegir nuestro equipo?',
    'team.stats.subtitle': 'Nuestro equipo diverso reúne experiencia de diferentes dominios para entregar soluciones integrales para las necesidades de tu negocio.',
    'team.stats.experience': 'Años de Experiencia Combinada',
    'team.stats.technologies': 'Tecnologías Dominadas',
    'team.stats.support': 'Soporte Disponible',
    'team.stats.satisfaction': 'Satisfacción del Cliente',
    'team.specializations.title': 'Nuestras Especializaciones',
    'team.specializations.frontend': 'Desarrollo Frontend',
    'team.specializations.backend': 'Desarrollo Backend',
    'team.specializations.fullstack': 'Desarrollo Full-Stack',
    'team.specializations.datascience': 'Ciencia de Datos',
    'team.specializations.mobile': 'Desarrollo Móvil',
    'team.specializations.devops': 'DevOps',
    'team.specializations.uiux': 'Diseño UI/UX',
    'team.specializations.aiml': 'Soluciones IA/ML',
    'team.specializations.cloud': 'Arquitectura en la Nube',
    'team.specializations.database': 'Diseño de Bases de Datos',
    
    // Clients translations
    'clients.title': 'Confiado por',
    'clients.titleHighlight': 'Empresas Líderes',
    'clients.subtitle': 'Hemos tenido el privilegio de trabajar con empresas increíbles de diferentes industrias, ayudándolas a alcanzar sus objetivos de transformación digital.',
    'clients.testimonials.title': 'Lo que dicen nuestros clientes',
    'clients.testimonials.ceo': 'CEO',
    'clients.testimonials.operations': 'Gerente de Operaciones',
    'clients.testimonials.production': 'Director de Producción',
    'clients.testimonials.testimonial1': 'Modware transformó nuestras operaciones minoristas con su innovadora plataforma de comercio electrónico. Las ventas aumentaron un 150% en el primer trimestre.',
    'clients.testimonials.testimonial2': 'El sistema de gestión farmacéutica que desarrollaron optimizó nuestro inventario y mejoró nuestra eficiencia dramáticamente.',
    'clients.testimonials.testimonial3': 'Sus soluciones de automatización redujeron nuestro tiempo de procesamiento en un 40% y eliminaron errores manuales en nuestro proceso de fabricación.',
    'clients.metrics.title': 'Nuestro Impacto en Números',
    'clients.metrics.subtitle': 'Resultados reales que importan para el éxito de nuestros clientes',
    'clients.metrics.sales': 'Aumento Promedio de Ventas',
    'clients.metrics.efficiency': 'Ganancia en Eficiencia de Procesos',
    'clients.metrics.uptime': 'Tiempo de Actividad del Sistema',
    'clients.metrics.support': 'Cobertura de Soporte',
    'clients.cta.title': '¿Listo para unirte a nuestras historias de éxito?',
    'clients.cta.subtitle': 'Hablemos sobre cómo podemos ayudar a tu negocio a lograr resultados similares. Programa una consulta gratuita hoy.',
    'clients.cta.button': 'Comienza tu historia de éxito',
    
    // Contact translations
    'contact.title': 'Comencemos Tu',
    'contact.titleHighlight': 'Viaje Digital',
    'contact.subtitle': '¿Listo para transformar tu negocio con tecnología de vanguardia? Contáctanos hoy para una consulta gratuita.',
    'contact.getInTouch.title': 'Ponte en Contacto',
    'contact.getInTouch.description': 'Estamos aquí para ayudarte a dar vida a tus ideas. Ya sea que necesites una aplicación personalizada, quieras automatizar tus procesos o explorar soluciones de IA, nuestro equipo está listo para asistirte.',
    'contact.info.location': 'Ubicación',
    'contact.info.locationValue': 'Popayán, Cauca, Colombia',
    'contact.info.website': 'Sitio Web',
    'contact.info.email': 'Correo Electrónico',
    'contact.info.hours': 'Horarios de Atención',
    'contact.info.hoursWeekdays': 'Lunes - Viernes: 8:00 AM - 6:00 PM (COT)',
    'contact.info.hoursSaturday': 'Sábado: 9:00 AM - 2:00 PM (COT)',
    'contact.quickContact.title': 'Contacto Rápido',
    'contact.quickContact.email': 'Envíanos un correo',
    'contact.quickContact.call': 'Llámanos directamente',
    'contact.quickContact.chat': 'Inicia un chat',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.name': 'Nombre Completo *',
    'contact.form.namePlaceholder': 'Tu nombre completo',
    'contact.form.email': 'Dirección de Correo *',
    'contact.form.emailPlaceholder': 'tu@correo.com',
    'contact.form.company': 'Empresa',
    'contact.form.companyPlaceholder': 'Nombre de tu empresa',
    'contact.form.phone': 'Número de Teléfono',
    'contact.form.phonePlaceholder': '+57 300 123 4567',
    'contact.form.service': 'Servicio de Interés',
    'contact.form.selectService': 'Selecciona un servicio',
    'contact.form.message': 'Mensaje *',
    'contact.form.messagePlaceholder': 'Cuéntanos sobre tu proyecto, requisitos o cualquier pregunta que tengas...',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.successTitle': '¡Mensaje Enviado Exitosamente!',
    'contact.form.successMessage': 'Gracias por contactarnos. Te responderemos dentro de 24 horas.',
    'contact.services.custom': 'Desarrollo de Software Personalizado',
    'contact.services.web': 'Aplicaciones Web',
    'contact.services.mobile': 'Aplicaciones Móviles',
    'contact.services.automation': 'Sistemas de Automatización',
    'contact.services.ai': 'Inteligencia Artificial',
    'contact.services.chatbots': 'Chatbots',
    'contact.services.crm': 'Sistemas CRM',
    'contact.services.billing': 'Facturación y Cobranza',
    'contact.services.other': 'Otro',
    'seo.company.description': 'Modware es una empresa colombiana de desarrollo de software con sede en Colombia, especializada en crear soluciones tecnológicas innovadoras para empresas locales e internacionales.',
    'seo.company.location': 'Ubicación:',
    'seo.company.specialty': 'Especialidad:',
    'seo.company.industries': 'Industrias:',
    'seo.company.technologies': 'Tecnologías:',
    'seo.why.title': '¿Por qué elegir Modware?',
    'seo.why.experience': 'Más de 6 años de experiencia en desarrollo de software',
    'seo.why.team': 'Equipo de desarrolladores certificados y especializados',
    'seo.why.methodology': 'Metodologías ágiles y entrega garantizada',
    'seo.why.support': 'Soporte técnico 24/7 y mantenimiento continuo',
    'seo.why.pricing': 'Precios competitivos y transparentes',
    
    // Team
    'team.title': 'Conoce Nuestro',
    'team.titleHighlight': 'Equipo Experto',
    'team.subtitle': 'Nuestro talentoso equipo de desarrolladores, diseñadores y científicos de datos están apasionados por crear soluciones innovadoras que impulsan el éxito empresarial.',
    'team.stats.title': '¿Por qué Elegir Nuestro Equipo?',
    'team.stats.subtitle': 'Nuestro equipo diverso reúne experiencia de diferentes dominios para entregar soluciones integrales para las necesidades de tu negocio.',
    'team.stats.experience': 'Años de Experiencia Combinada',
    'team.stats.technologies': 'Tecnologías Dominadas',
    'team.stats.support': 'Soporte Disponible',
    'team.stats.satisfaction': 'Satisfacción del Cliente',
    'team.specializations': 'Nuestras Especializaciones',
    
    // Clients
    'clients.title': 'Confianza de',
    'clients.titleHighlight': 'Empresas Líderes',
    'clients.subtitle': 'Hemos tenido el privilegio de trabajar con empresas increíbles de diferentes industrias, ayudándolas a alcanzar sus objetivos de transformación digital.',
    'clients.testimonials': 'Lo que Dicen Nuestros Clientes',
    'clients.impact.title': 'Nuestro Impacto en Números',
    'clients.impact.subtitle': 'Resultados reales que importan para el éxito de nuestros clientes',
    'clients.impact.sales': 'Aumento Promedio de Ventas',
    'clients.impact.efficiency': 'Ganancia en Eficiencia de Procesos',
    'clients.impact.uptime': 'Tiempo de Actividad del Sistema',
    'clients.impact.support': 'Cobertura de Soporte',
    'clients.cta.title': '¿Listo para Unirte a Nuestras Historias de Éxito?',
    'clients.cta.subtitle': 'Hablemos sobre cómo podemos ayudar a tu negocio a lograr resultados similares. Programa una consulta gratuita hoy.',
    'clients.cta.button': 'Comienza tu Historia de Éxito',
    
    // Contact
    'contact.title': 'Comencemos tu',
    'contact.titleHighlight': 'Viaje Digital',
    'contact.subtitle': '¿Listo para transformar tu negocio con tecnología de vanguardia? Ponte en contacto con nosotros hoy para una consulta gratuita.',
    'contact.getInTouch': 'Ponte en Contacto',
    'contact.description': 'Estamos aquí para ayudarte a dar vida a tus ideas. Ya sea que necesites una aplicación personalizada, quieras automatizar tus procesos o explorar soluciones de IA, nuestro equipo está listo para asistirte.',
    'contact.location': 'Ubicación',
    'contact.website': 'Sitio Web',
    'contact.email': 'Correo',
    'contact.hours': 'Horario de Atención',
    'contact.hours.weekdays': 'Lunes - Viernes: 8:00 AM - 6:00 PM (COT)',
    'contact.hours.saturday': 'Sábado: 9:00 AM - 2:00 PM (COT)',
    'contact.quickContact': 'Contacto Rápido',
    'contact.sendEmail': 'Envíanos un correo',
    'contact.callDirect': 'Llámanos directamente',
    'contact.startChat': 'Iniciar chat',
    'contact.form.title': 'Envíanos un Mensaje',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.company': 'Empresa',
    'contact.form.phone': 'Teléfono',
    'contact.form.service': 'Servicio de Interés',
    'contact.form.message': 'Mensaje',
    'contact.form.send': 'Enviar Mensaje',
    'contact.form.success.title': '¡Mensaje Enviado Exitosamente!',
    'contact.form.success.subtitle': 'Gracias por contactarnos. Te responderemos en 24 horas.',
    'contact.form.placeholder.name': 'Tu nombre completo',
    'contact.form.placeholder.email': 'tu@correo.com',
    'contact.form.placeholder.company': 'Nombre de tu empresa',
    'contact.form.placeholder.phone': '+57 300 123 4567',
    'contact.form.placeholder.message': 'Cuéntanos sobre tu proyecto, requisitos o cualquier pregunta que tengas...',
    'contact.form.selectService': 'Selecciona un servicio',
    'contact.services.custom': 'Desarrollo de Software Personalizado',
    'contact.services.web': 'Aplicaciones Web',
    'contact.services.mobile': 'Aplicaciones Móviles',
    'contact.services.automation': 'Sistemas de Automatización',
    'contact.services.ai': 'Inteligencia Artificial',
    'contact.services.chatbots': 'Chatbots',
    'contact.services.crm': 'Sistemas CRM',
    'contact.services.billing': 'Facturación y Cobranza',
    'contact.services.other': 'Otro',
    
    // Footer
    'footer.description': 'Transformando negocios a través de soluciones de software innovadoras. Construimos aplicaciones personalizadas, automatizamos procesos e implementamos tecnologías de IA de vanguardia.',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.services': 'Nuestros Servicios',
    'footer.getInTouch': 'Ponte en Contacto',
    'footer.followUs': 'Síguenos',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.madeWith': 'Hecho con',
    'footer.madeIn': 'en Colombia',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    
    // Services Data
    'services.data.1.title': 'Desarrollo de Software Personalizado',
    'services.data.1.description': 'Soluciones de software a medida diseñadas para satisfacer las necesidades específicas de tu negocio.',
    'services.data.1.feature1': 'Arquitectura Personalizada',
    'services.data.1.feature2': 'Soluciones Escalables',
    'services.data.1.feature3': 'Tecnologías Modernas',
    'services.data.2.title': 'Aplicaciones Web',
    'services.data.2.description': 'Aplicaciones web modernas y responsivas construidas con tecnologías de vanguardia y mejores prácticas.',
    'services.data.2.feature1': 'Diseño Responsivo',
    'services.data.2.feature2': 'Aplicaciones Web Progresivas',
    'services.data.2.feature3': 'Optimizado para SEO',
    'services.data.3.title': 'Aplicaciones Móviles',
    'services.data.3.description': 'Aplicaciones móviles nativas y multiplataforma para dispositivos iOS y Android.',
    'services.data.3.feature1': 'Multiplataforma',
    'services.data.3.feature2': 'Rendimiento Nativo',
    'services.data.3.feature3': 'Listo para App Store',
    'services.data.4.title': 'Sistemas de Automatización',
    'services.data.4.description': 'Soluciones de automatización inteligente para optimizar procesos empresariales y aumentar la eficiencia.',
    'services.data.4.feature1': 'Automatización de Procesos',
    'services.data.4.feature2': 'Optimización de Flujos',
    'services.data.4.feature3': 'Listo para Integración',
    'services.data.5.title': 'Inteligencia Artificial',
    'services.data.5.description': 'Soluciones impulsadas por IA incluyendo aprendizaje automático, análisis de datos y toma de decisiones inteligente.',
    'services.data.5.feature1': 'Aprendizaje Automático',
    'services.data.5.feature2': 'Análisis de Datos',
    'services.data.5.feature3': 'Modelos Predictivos',
    'services.data.6.title': 'Chatbots',
    'services.data.6.description': 'Interfaces conversacionales inteligentes para mejorar el servicio al cliente y la participación del usuario.',
    'services.data.6.feature1': 'Procesamiento de Lenguaje Natural',
    'services.data.6.feature2': 'Disponibilidad 24/7',
    'services.data.6.feature3': 'Multiplataforma',
    'services.data.7.title': 'Sistemas CRM',
    'services.data.7.description': 'Sistemas de gestión de relaciones con clientes para optimizar ventas e interacciones con clientes.',
    'services.data.7.feature1': 'Gestión de Prospectos',
    'services.data.7.feature2': 'Pipeline de Ventas',
    'services.data.7.feature3': 'Análisis de Clientes',
    'services.data.8.title': 'Facturación y Cobros',
    'services.data.8.description': 'Soluciones integrales de facturación y cobros para una gestión financiera eficiente.',
    'services.data.8.feature1': 'Facturación Automatizada',
    'services.data.8.feature2': 'Integración de Pagos',
    'services.data.8.feature3': 'Reportes Financieros',
    
    // Common
    'common.required': '*',
    'common.optional': '(Opcional)',
  },
  en: {
    // Header
    'header.home': 'Home',
    'header.services': 'Services',
    'header.team': 'Team',
    'header.clients': 'Clients',
    'header.contact': 'Contact',
    'header.getStarted': 'Get Started',
    
    // Hero
    'hero.location': 'Popayán, Cauca, Colombia',
    'hero.title': 'Transforming Ideas into',
    'hero.titleHighlight': 'Digital Solutions',
    'hero.subtitle': 'We are Modware, a Colombian software development company specializing in custom applications, AI solutions, and digital transformation.',
    'hero.exploreServices': 'Explore Our Services',
    'hero.startProject': 'Start Your Project',
    'hero.developers': 'Expert Developers',
    'hero.projects': 'Projects Delivered',
    'hero.clients': 'Happy Clients',
    'hero.experience': 'Years Experience',
    
    // Services
    'services.title': 'Our',
    'services.titleHighlight': 'Services',
    'services.subtitle': 'We offer comprehensive software development services to help your business thrive in the digital age. From custom applications to AI solutions.',
    'services.cta.title': 'Ready to Transform Your Business?',
    'services.cta.subtitle': 'Let\'s discuss how our expertise can help you achieve your digital goals. Get a free consultation and project estimate.',
    'services.cta.consultation': 'Get Free Consultation',
    'services.cta.quote': 'Request Quote',
    'services.technologies': 'Technologies We Master',
    
    // SEO
    'seo.title': 'Software Development in Colombia',
    'seo.subtitle': 'We are a Colombian company specialized in mobile app development, web applications, and artificial intelligence solutions for businesses of all sizes.',
    'seo.mobile.title': 'Mobile Application Development',
    'seo.mobile.description': 'We create native and hybrid mobile applications for iOS and Android using the latest technologies like Flutter, React Native, and native development.',
    'seo.web.title': 'Professional Web Development',
    'seo.web.description': 'We develop modern, responsive, and SEO-optimized websites and web applications using technologies like React, Angular, Vue.js, and Node.js.',
    'seo.ai.title': 'Artificial Intelligence and Machine Learning',
    'seo.ai.description': 'We implement custom AI solutions, intelligent chatbots, data analysis, and business process automation.',
    'seo.company.title': 'About Modware',
    'seo.company.about.title': 'Our Company',
    'seo.company.about.description': 'Modware is a software development company based in Colombia, specialized in creating innovative technological solutions for businesses across all sectors.',
    'seo.company.about.location': 'Bogotá, Colombia',
    'seo.company.about.team': 'Expert development team',
    'seo.company.about.projects': 'Successful projects delivered',
    'seo.company.services.title': 'Our Services',
    'seo.company.services.mobile': 'iOS and Android mobile app development',
    'seo.company.services.web': 'Web development with React, Angular, and Vue.js',
    'seo.company.services.ai': 'Artificial intelligence solutions',
    'seo.company.services.consulting': 'Digital transformation consulting',
    'seo.company.services.support': 'Maintenance and technical support',
    
    // Team translations
    'team.title': 'Meet Our',
    'team.titleHighlight': 'Expert Team',
    'team.subtitle': 'Our talented team of developers, designers, and data scientists are passionate about creating innovative solutions that drive business success.',
    'team.stats.title': 'Why Choose Our Team?',
    'team.stats.subtitle': 'Our diverse team brings together expertise from different domains to deliver comprehensive solutions for your business needs.',
    'team.stats.experience': 'Years Combined Experience',
    'team.stats.technologies': 'Technologies Mastered',
    'team.stats.support': 'Support Available',
    'team.stats.satisfaction': 'Client Satisfaction',
    'team.specializations.title': 'Our Specializations',
    'team.specializations.frontend': 'Frontend Development',
    'team.specializations.backend': 'Backend Development',
    'team.specializations.fullstack': 'Full-Stack Development',
    'team.specializations.datascience': 'Data Science',
    'team.specializations.mobile': 'Mobile Development',
    'team.specializations.devops': 'DevOps',
    'team.specializations.uiux': 'UI/UX Design',
    'team.specializations.aiml': 'AI/ML Solutions',
    'team.specializations.cloud': 'Cloud Architecture',
    'team.specializations.database': 'Database Design',
    
    // Clients translations
    'clients.title': 'Trusted by',
    'clients.titleHighlight': 'Leading Companies',
    'clients.subtitle': 'We\'ve had the privilege of working with amazing companies across different industries, helping them achieve their digital transformation goals.',
    'clients.testimonials.title': 'What Our Clients Say',
    'clients.testimonials.ceo': 'CEO',
    'clients.testimonials.operations': 'Operations Manager',
    'clients.testimonials.production': 'Production Director',
    'clients.testimonials.testimonial1': 'Modware transformed our retail operations with their innovative e-commerce platform. Sales increased by 150% in the first quarter.',
    'clients.testimonials.testimonial2': 'The pharmaceutical management system they developed streamlined our inventory and improved our efficiency dramatically.',
    'clients.testimonials.testimonial3': 'Their automation solutions reduced our processing time by 40% and eliminated manual errors in our manufacturing process.',
    'clients.metrics.title': 'Our Impact in Numbers',
    'clients.metrics.subtitle': 'Real results that matter to our clients\' success',
    'clients.metrics.sales': 'Average Sales Increase',
    'clients.metrics.efficiency': 'Process Efficiency Gain',
    'clients.metrics.uptime': 'System Uptime',
    'clients.metrics.support': 'Support Coverage',
    'clients.cta.title': 'Ready to Join Our Success Stories?',
    'clients.cta.subtitle': 'Let\'s discuss how we can help your business achieve similar results. Schedule a free consultation today.',
    'clients.cta.button': 'Start Your Success Story',
    'seo.company.description': 'Modware is a Colombian software development company based in Colombia, specialized in creating innovative technological solutions for local and international businesses.',
    'seo.company.location': 'Location:',
    'seo.company.specialty': 'Specialty:',
    'seo.company.industries': 'Industries:',
    'seo.company.technologies': 'Technologies:',
    'seo.why.title': 'Why choose Modware?',
    'seo.why.experience': 'More than 6 years of experience in software development',
    'seo.why.team': 'Team of certified and specialized developers',
    'seo.why.methodology': 'Agile methodologies and guaranteed delivery',
    'seo.why.support': '24/7 technical support and continuous maintenance',
    'seo.why.pricing': 'Competitive and transparent pricing',
    
    // Team
    'team.title': 'Meet Our',
    'team.titleHighlight': 'Expert Team',
    'team.subtitle': 'Our talented team of developers, designers, and data scientists are passionate about creating innovative solutions that drive business success.',
    'team.stats.title': 'Why Choose Our Team?',
    'team.stats.subtitle': 'Our diverse team brings together expertise from different domains to deliver comprehensive solutions for your business needs.',
    'team.stats.experience': 'Years Combined Experience',
    'team.stats.technologies': 'Technologies Mastered',
    'team.stats.support': 'Support Available',
    'team.stats.satisfaction': 'Client Satisfaction',
    'team.specializations': 'Our Specializations',
    
    // Clients
    'clients.title': 'Trusted by',
    'clients.titleHighlight': 'Leading Companies',
    'clients.subtitle': 'We\'ve had the privilege of working with amazing companies across different industries, helping them achieve their digital transformation goals.',
    'clients.testimonials': 'What Our Clients Say',
    'clients.impact.title': 'Our Impact in Numbers',
    'clients.impact.subtitle': 'Real results that matter to our clients\' success',
    'clients.impact.sales': 'Average Sales Increase',
    'clients.impact.efficiency': 'Process Efficiency Gain',
    'clients.impact.uptime': 'System Uptime',
    'clients.impact.support': 'Support Coverage',
    'clients.cta.title': 'Ready to Join Our Success Stories?',
    'clients.cta.subtitle': 'Let\'s discuss how we can help your business achieve similar results. Schedule a free consultation today.',
    'clients.cta.button': 'Start Your Success Story',
    
    // Contact
    'contact.title': 'Let\'s Start Your',
    'contact.titleHighlight': 'Digital Journey',
    'contact.subtitle': 'Ready to transform your business with cutting-edge technology? Get in touch with us today for a free consultation.',
    'contact.getInTouch': 'Get in Touch',
    'contact.description': 'We\'re here to help you bring your ideas to life. Whether you need a custom application, want to automate your processes, or explore AI solutions, our team is ready to assist you.',
    'contact.location': 'Location',
    'contact.website': 'Website',
    'contact.email': 'Email',
    'contact.hours': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Friday: 8:00 AM - 6:00 PM (COT)',
    'contact.hours.saturday': 'Saturday: 9:00 AM - 2:00 PM (COT)',
    'contact.quickContact': 'Quick Contact',
    'contact.sendEmail': 'Send us an email',
    'contact.callDirect': 'Call us directly',
    'contact.startChat': 'Start a chat',
    'contact.form.title': 'Send us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company',
    'contact.form.phone': 'Phone Number',
    'contact.form.service': 'Service of Interest',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.success.title': 'Message Sent Successfully!',
    'contact.form.success.subtitle': 'Thank you for reaching out. We\'ll get back to you within 24 hours.',
    'contact.form.placeholder.name': 'Your full name',
    'contact.form.placeholder.email': 'your@email.com',
    'contact.form.placeholder.company': 'Your company name',
    'contact.form.placeholder.phone': '+57 300 123 4567',
    'contact.form.placeholder.message': 'Tell us about your project, requirements, or any questions you have...',
    'contact.form.selectService': 'Select a service',
    
    // Footer
    'footer.description': 'Transforming businesses through innovative software solutions. We build custom applications, automate processes, and implement cutting-edge AI technologies.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.getInTouch': 'Get in Touch',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    'footer.madeWith': 'Made with',
    'footer.madeIn': 'in Colombia',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    
    // Services Data
    'services.data.1.title': 'Custom Software Development',
    'services.data.1.description': 'Tailored software solutions designed to meet your specific business needs and requirements.',
    'services.data.1.feature1': 'Custom Architecture',
    'services.data.1.feature2': 'Scalable Solutions',
    'services.data.1.feature3': 'Modern Technologies',
    'services.data.2.title': 'Web Applications',
    'services.data.2.description': 'Modern, responsive web applications built with cutting-edge technologies and best practices.',
    'services.data.2.feature1': 'Responsive Design',
    'services.data.2.feature2': 'Progressive Web Apps',
    'services.data.2.feature3': 'SEO Optimized',
    'services.data.3.title': 'Mobile Applications',
    'services.data.3.description': 'Native and cross-platform mobile applications for iOS and Android devices.',
    'services.data.3.feature1': 'Cross-Platform',
    'services.data.3.feature2': 'Native Performance',
    'services.data.3.feature3': 'App Store Ready',
    'services.data.4.title': 'Automation Systems',
    'services.data.4.description': 'Intelligent automation solutions to streamline your business processes and increase efficiency.',
    'services.data.4.feature1': 'Process Automation',
    'services.data.4.feature2': 'Workflow Optimization',
    'services.data.4.feature3': 'Integration Ready',
    'services.data.5.title': 'Artificial Intelligence',
    'services.data.5.description': 'AI-powered solutions including machine learning, data analysis, and intelligent decision making.',
    'services.data.5.feature1': 'Machine Learning',
    'services.data.5.feature2': 'Data Analytics',
    'services.data.5.feature3': 'Predictive Models',
    'services.data.6.title': 'Chatbots',
    'services.data.6.description': 'Intelligent conversational interfaces to enhance customer service and user engagement.',
    'services.data.6.feature1': 'Natural Language Processing',
    'services.data.6.feature2': '24/7 Availability',
    'services.data.6.feature3': 'Multi-Platform',
    'services.data.7.title': 'CRM Systems',
    'services.data.7.description': 'Customer relationship management systems to optimize your sales and customer interactions.',
    'services.data.7.feature1': 'Lead Management',
    'services.data.7.feature2': 'Sales Pipeline',
    'services.data.7.feature3': 'Customer Analytics',
    'services.data.8.title': 'Billing & Invoicing',
    'services.data.8.description': 'Comprehensive billing and invoicing solutions for efficient financial management.',
    'services.data.8.feature1': 'Automated Billing',
    'services.data.8.feature2': 'Payment Integration',
    'services.data.8.feature3': 'Financial Reports',
    
    // Common
    'common.required': '*',
    'common.optional': '(Optional)',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};